usb_hal_o += $(addprefix ../usb_hal/, $(USB_HAL))
usbdisp_drm-y := msdisp_plat_drv.o msdisp_plat_dev.o msdisp_drm_drv.o \
	msdisp_drm_modeset.o msdisp_drm_gem.o msdisp_drm_fb.o \
	msdisp_drm_encoder.o msdisp_drm_connector.o msdisp_drm_interface.o \
	msdisp_drm_sysfs.o msdisp_common_util.o msdisp_drm_mode.o
usbdisp_usb-y := msdisp_usb_drv.o ms9132_hal.o $(usb_hal_o)
obj-m :=

ifneq ($(usbdisp_drm-y),)
obj-m += usbdisp_drm.o
endif

ifneq ($(usbdisp_usb-y),)
obj-m += usbdisp_usb.o
endif

ccflags-y := -isystem include/drm -I$(HAL_PATH) $(CFLAGS) $(EL8FLAG) $(RPIFLAG)
CFLAGS_usbdisp_usb.o += -I$(HAL_PATH)
